# Generated by Django 3.2.9 on 2021-12-20 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=64)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_lists', to='cash_candy_app.child')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_location', models.CharField(max_length=64)),
                ('item_id', models.CharField(max_length=64, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.CharField(blank=True, max_length=32, null=True)),
                ('purchased', models.BooleanField(default=False)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cash_candy_app.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_list_name', models.CharField(max_length=64)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_lists', to='cash_candy_app.child')),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_description', models.TextField()),
                ('transaction_date', models.CharField(max_length=64)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allowancelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_detail', to='cash_candy_app.allowancelist')),
            ],
        ),
    ]
