# Generated by Django 3.2.9 on 2021-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_candy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancedetail',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
